### PR TITLE
Switch from labs.waterdata to api.water

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
We've fully migrated our production services to api.water.usgs.gov and I'd like to update the redirects and various links in geoconnex. I think I got them all.

I was not able to rebuild the demo.html as various links are now stale in that demo.

### CODE REVIEW

**Comment by webb-ben** [comment]
Should we prune demo.html then?

**Comment by dblodgett-usgs** [comment]
I don't know. I think @ksonda built it. Is it still needed?

**Comment by ksonda** [comment]
We don't need it any more, superseded by various things on docs.geoconnex.us

**Comment by dblodgett-usgs** [comment]
OK, Looking now, there are links to it in a few places. Created #245 to track that.

**Comment by webb-ben** [comment]
We can address that and further repository cleaning in a subsequent PR. +1 from me

**Review by webb-ben — APPROVED** [review]

**Pull request merged**
