### PR TITLE
Add a geospatial fabric namespace

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
This is kind of a pilot -- will update it before too long, but the usgs/gfv11_pois namespace with a regex redirect will be pretty stable.

### CODE REVIEW

**Comment by ksonda** [comment]
I believe there are a few things wrong with this.

a) I believe the features you are pointing to use this identifier scheme in the field 'uri': https://geoconnex.us/usgs/GFV_1_1/{prvdr_d} 

but your request is for https://geoconnex.us/usgs/gfv11_pois/{x}

for example you have  https://geoconnex.us/usgs/gfv11_pois/6742250 pointing to a feature with ```"uri":"https://geoconnex.us/usgs/GFV_1_1/1"```

b) In your layer, sbjctOf points to https://www.sciencebase.gov/catalog/item/5e29b87fe4b0a79317cf7df5, not the corresponding feature (WFS call). This is more of a check, not sure if this is desired

**Comment by dblodgett-usgs** [comment]
Thanks for the thorough review.
a)  I need to update the WFS to use the PID pattern here. 
b) I do want the subjectOf to point to that dataset 
c) please don't merge until I've fixed the README -- this is kind of a WIP.
d) good tip. I'll get that fixed in the csv in my next commit.

**Comment by dblodgett-usgs** [comment]
OK -- I think I have this where it needs to be to merge.

**Comment by ksonda** [comment]
Ça marche!

**Pull request merged**
