### PR TITLE
started nmwdi

### PR DESCRIPTION
**Pull request by jirhiker**

### CODE REVIEW

**Comment by ksonda** [comment]
For this to work you need to set the URI to end in the {NMWDI-} based ids.

image

**Comment by jirhiker** [comment]
small issue.   NMWDI-0000001 is Location name I minted during ETL. However I don't mint new names for the Things associated with each Location. I use the agency identifier (e.g. AR-0001).

Ill replace the location name the thing name.  but that means URI will end with agency based ids

**Comment by ksonda** [comment]
Ok. The other alternative is to just set id_field: in wdi.config.yml to agency_id .

**Comment by ksonda** [comment]
OK. I'm going to merge this and interpret it as a regex redirect. @dblodgett-usgs I think it's actually easy enough to, if the person knows regex, to implement these as csv template as well. I'll tinker with it.

**Pull request merged**
