### PR TITLE
Update reference.geoconnex.us CI/CD to CloudSQL backend

### PR DESCRIPTION
**Pull request by webb-ben**
Update pygeoapi-ci.yml, pygeoapi.config.yml to serve geoconnex.us over GCP with Cloud SQL

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
@webb-ben where is the postgres loading code that creates the tables referenced in the configuration here?

**Comment by webb-ben** [comment]
@dblodgett-usgs [cgs-earth/hydrodump-action@0.3.0](https://github.com/cgs-earth/hydrodump-action) github action creates a `.sql.gz` backup of the result of posting (ogr2ogr) files from a Hydroshare resource

**Comment by dblodgett-usgs** [comment]
ok -- so how do we know what valid table names are? Just through knowledge of what's over there?

**Comment by webb-ben** [comment]
Table name is the name of the file without the filetype. [This is the ogr2ogr invocation](https://github.com/cgs-earth/hydrodump-action/blob/master/hydrodump/hydrodump/hydrodump.py#L76-L80)

Have only tried using GPKG so I am not quite sure how it looks for other files. I'm trying to keep the Hydrodump action as generic as possible but there is also a world where it could be passed a pygeoapi configuration file and then use the provider information to inform the table name. Could even get the source file to download from the resource links section which could be anywhere...

**Comment by ksonda** [comment]
That's not a bad idea, then people only need to edit the config file

**Comment by ksonda** [comment]
I think for the sake of our CI/CD we should merrge this now. However, I take @dblodgett-usgs point that we need a registry for where source files live and what the table name in postgis is. I also take @webb-ben point that we either need to clean up the hydroshare resource or implement a system where reference features source files can live at any URL, which can exist in the aforementioned registry or be part of pygeoapi config.yml TBD. I will an open an issue to address this.

**Pull request merged**
