### PR TITLE
PIDs for almost all CUAHSI HIS data providers

### PR DESCRIPTION
**Pull request by Castronova**
This pull request contains PIDs, formatted in CSV files, for almost all CUAHSI HIS data providers. Several data providers have been omitted due to GitHub file size limitations (e.g. NWIS GW). Several other providers have been omitted due to an outstanding issue in the wateroneflow services that needs to be resolved. This will be included in a separate PR.

### CODE REVIEW

**Comment by ksonda** [comment]
Awesome @Castronova !

For the PID sets that are too large, please consider submitting a regex redirect request issue.

**Comment by ksonda** [comment]
Upon further review, the jsonld ```@id``` fields are selfie.cuahsi.org URLs. I think @dblodgett-usgs wants these to be geoconnex PIDs if possible

**Comment by dblodgett-usgs** [comment]
This is great. And yeah, for the big lists, we should think about regex redirects. Having them be explicit is nice, but the more we've worked with these lists, the more it's becoming clear that maintenance of the list is more overhead than it's worth when we can get away with pattern matching.

The `@id` fields should indeed point to the persistent identifier. 

Also, if possible, we should put the context content inline in the JSON-LD. We realized just this week that google doesn't resolve linked contexts... As you can see here: https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Fselfie.cuahsi.org%2FCALVIN_HHS%2FSR-1 

I just did some editing on the structured data in that landing page to get it closer to "happy" for google.

```
{
  "@context": {
    "schema": "http://schema.org/",
    "gsp": "http://www.opengeospatial.org/standards/geosparql/",
    "hyf": "https://www.opengis.net/def/appschema/hy_features/hyf/",
    "name": "schema:name",
    "description": "schema:description",
    "geo": "schema:geo"
  },
  "@id": "https://geoconnex.us/cuahsi/his/CALVIN_HHS/SR-1",
  "@type": [
    "hyf:HY_HydroLocation",
    "schema:Place"
  ],
  "hyf:HY_HydroLocationType": "hyf:hydrometricStation",
  "description": "SR-1 - CALVIN_HHS - SR-1",
  "geo": {
    "@type": "schema:GeoCoordinates",
    "schema:latitude": 40.801,
    "schema:longitude": -122.762
  },
  "gsp:hasGeometry": {
    "@type": "gsp:Geometry",
    "gsp:asWKT": "POINT (-122.762 40.801)"
  },
  "name": "SR-1 - CALVIN_HHS"
}
```

This is going to be a work in progress for a while but this is a great start!!

**Comment by ksonda** [comment]
code running to post these PIDs now. I'll make a new issue about the structured data

**Pull request merged**
